apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-geoserver-conf
  namespace: {{ .Release.Namespace }}
data:
  notifier.xml: |
    <notificationConfiguration>
      <queueSize>1000</queueSize>
      <notificator>
        <queueSize>1000</queueSize>
        <processorThreads>1</processorThreads>
        <messageFilter>type='Catalog'</messageFilter>
        <genericProcessor>
          <geonodeEncoder />
          <topicSender>
            <username>{{ .Values.rabbitmq.auth.username }}</username>
            <password>{{ .Values.rabbitmq.auth.password }}</password>
            <host>{{ .Release.Name }}-rabbitmq</host>
            <port>5672</port>
            <virtualHost>/</virtualHost>
            <exchangeName>geonode</exchangeName>
            <routingKey>geoserver.catalog</routingKey>
          </topicSender>
        </genericProcessor>
      </notificator>
      <notificator>
        <queueSize>1000</queueSize>
        <processorThreads>10</processorThreads>
        <messageFilter>type='Data'</messageFilter>
        <genericProcessor>
          <geonodeEncoder />
          <topicSender>
            <username>{{ .Values.rabbitmq.auth.username }}</username>
            <password>{{ .Values.rabbitmq.auth.password }}</password>
            <host>{{ .Release.Name }}-rabbitmq</host>
            <port>5672</port>
            <virtualHost>/</virtualHost>
            <exchangeName>geonode</exchangeName>
            <routingKey>geoserver.data</routingKey>
          </topicSender>
        </genericProcessor>
      </notificator>
    </notificationConfiguration>