apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.general.serviceType }}
  ports:
    - name: api
      port: 8080
      targetPort: 8080
  selector:
    org.apicurio.instance: {{ .Release.Name }}-api
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ui
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.general.serviceType }}
  ports:
    - name: ui
      port: 8080
      targetPort: 8080
  selector:
    org.apicurio.instance: {{ .Release.Name }}-ui
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ws
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.general.serviceType }}
  ports:
    - name: ws
      port: 8080
      targetPort: 8080
  selector:
    org.apicurio.instance: {{ .Release.Name }}-ws
