{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    org.apicurio.instance: {{ .Release.Name }}-api
  {{- with .Values.api.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.api.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.api.ingress.path }}
            pathType: {{ .Values.api.ingress.pathType }}
            backend:
              service:
                name: {{ .Release.Name }}-api
                port:
                  number: 8080
  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ui
  namespace: {{ .Release.Namespace }}
  labels:
    org.apicurio.instance: {{ .Release.Name }}-ui
  {{- with .Values.ui.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ui.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ui.ingress.path }}
            pathType: {{ .Values.ui.ingress.pathType }}
            backend:
              service:
                name: {{ .Release.Name }}-ui
                port:
                  number: 8080
  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ws
  namespace: {{ .Release.Namespace }}
  labels:
    org.apicurio.instance: {{ .Release.Name }}-ws
  {{- with .Values.ws.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ws.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ws.ingress.path }}
            pathType: {{ .Values.ws.ingress.pathType }}
            backend:
              service:
                name: {{ .Release.Name }}-ws
                port:
                  number: 8080
  {{- if .Values.ingress.tlsSecretName }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
{{- end }}
