apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    org.apicurio.instance: {{ .Release.Name }}-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      org.apicurio.instance: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        org.apicurio.instance: {{ .Release.Name }}-api
      annotations:
        # Force a pod restart if secret values change
        checksum/secrets: {{ include "secrets_api" . | sha256sum }}
    spec:
      securityContext:
        {{- .Values.api.securityContext | toYaml | nindent 8 }}
      restartPolicy: Always

      initContainers:
        {{- if .Values.api.wait }}
        # Wait for db
        - name: wait-db
          image: jwilder/dockerize
          imagePullPolicy: IfNotPresent
          args:
            - -timeout=300s
            - -wait=tcp://{{ include "dbHost" . }}:{{ .Values.postgresql.service.port }}
        {{- end }}

      containers:
        - name: api
          image: "{{ .Values.api.image.name }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.imagePullPolicy }}
          terminationMessagePolicy: FallbackToLogsOnError
          env:
            # DB settings
            - name: APICURIO_DB_CONNECTION_URL
              value: {{ include "dbUrl" . | quote }}
            - name: APICURIO_DB_DRIVER_NAME
              value: {{ .Values.database.driver | quote }}
            - name: APICURIO_DB_INITIALIZE
              value: {{ .Values.database.initialize | quote }}
            - name: APICURIO_DB_TYPE
              value: {{ .Values.database.type | quote }}
            - name: APICURIO_DB_USER_NAME
              value: {{ .Values.postgresql.postgresqlUsername | quote }}

            # Microcks settings
            - name: APICURIO_MICROCKS_API_URL
              value: {{ .Values.microcks.api.url | quote }}
            - name: APICURIO_MICROCKS_CLIENT_ID
              value: {{ .Values.microcks.client.id | quote }}

            # Keycloak settings
            - name: APICURIO_KC_AUTH_URL
              value: {{ .Values.keycloak.url | quote }}
            - name: APICURIO_KC_REALM
              value: {{ .Values.keycloak.realm | quote }}
            - name: APICURIO_KC_CLIENT_ID
              value: {{ .Values.keycloak.client.id | quote }}

            # Others
            - name: APICURIO_SHARE_FOR_EVERYONE
              value: {{ .Values.general.shareForEveryone | quote }}

            {{- range $key, $value := .Values.api.extraEnvVars }}
            - name: {{ $key }}
              value: |-
                {{- tpl $value $ | nindent 16 }}
            {{- end }}

          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-api

          ports:
            - containerPort: 8080

          readinessProbe:
            {{- include "httpProbe" "/system/ready" | nindent 12 }}
          livenessProbe:
            {{- include "httpProbe" "/system/ready" | nindent 12 }}
