apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- include "secrets_api" . | nindent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ui
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- include "secrets_ui" . | nindent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ws
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- include "secrets_ws" . | nindent 2 }}
