DEFAULT_BRANCH: main

ENABLE_LINTERS:
  - DOCKERFILE_HADOLINT
  - JSON_PRETTIER
  - JSON_JSONLINT
  - JSON_V8R
  - YAML_V8R
  - YAML_PRETTIER
  - YAML_YAMLLINT

YAML_PRETTIER_FILTER_REGEX_EXCLUDE: .github/*
YAML_V8R_FILTER_REGEX_EXCLUDE: .github/*
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: .github/*

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
PRINT_ALPACA: false
