{{- if .Values.microcks.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "microcks.mongodb.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microcks.mongodb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
