{{- if .Values.microcks.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microcks.mongodb.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "microcks.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.microcks.secrets.mongodb }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  mongodb-usernames: {{ .Values.microcks.mongodb.env.MONGODB_EXTRA_USERNAMES | b64enc | quote }}
{{- end }}
