apiVersion: v1
kind: Secret
metadata:
    name:  {{ include "uptime-wrapper.fullname" . }}-secret
type: Opaque
data:
    ADMIN_PASSWORD: {{ .Values.env.ADMIN_PASSWORD | b64enc }}
    KUMA_PASSWORD: {{ .Values.env.KUMA_PASSWORD | b64enc }}
    SECRET_KEY: {{ .Values.env.SECRET_KEY | b64enc }}