{{- if .Values.ingress.enabled -}}
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /fineract-provider
            pathType: Prefix
            backend:
              serviceName: {{ .Release.Name }}-backend
              servicePort: http
          {{- if or .Values.mifosx.enabled .Values.ui.enabled }}
          - path: /
            pathType: Prefix
            backend:
            {{- if .Values.mifosx.enabled }}
              serviceName: {{ .Release.Name }}-mifosx
              servicePort: http
            {{- else }}
              serviceName: {{ .Release.Name }}-ui
              servicePort: 80
            {{- end }}
          {{- end }}
  {{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
{{- end -}}
