apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautic.fullname" . | quote }}
  labels:
    {{- include "mautic.labels" . | nindent 4 }}
data:
  MAUTIC_DB_PASSWORD: {{ .Values.mariadb.auth.password | b64enc }}
  {{- range $key, $value := .Values.extraSecretEnvs }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
