{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.appOriginName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "growthbook.fullname" . }}
                port: 
                  number: {{ .Values.port.frontendPort }}
    - host: {{ .Values.ingress.apiHostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "growthbook.fullname" . }}
                port:
                  number: {{ .Values.port.backendPort }}
    {{- if .Values.growthbookProxy.enabled }}
    - host: {{ .Values.ingress.apiProxyHostName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "growthbook.fullname" . }}-proxy
                port:
                  number: {{ .Values.port.proxyPort }}
    {{- end }}
  tls:
    - hosts:
        - {{ .Values.ingress.appOriginName }}
        - {{ .Values.ingress.apiHostName }}
        {{- if .Values.growthbookProxy.enabled }}
        - {{ .Values.ingress.apiProxyHostName }}
        {{- end }}
      secretName: {{ .Values.ingress.secretName }}
{{- end -}}