{{- if .Values.growthbookSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "growthbook.secretName" . }}
  labels:
    {{- include "growthbook.labels" . | nindent 4 }}
type: Opaque
data:
  MONGODB_URI: {{ include "growthbook.mongo.uri" . | default "" | b64enc | quote }}
  JWT_SECRET: {{ .Values.growthbook.jwtSecret | default "" | b64enc | quote }}
  ENCRYPTION_KEY: {{ .Values.growthbook.encryptionKey | default "" | b64enc | quote }}
  {{- if .Values.growthbook.email.enabled }}
  EMAIL_HOST_PASSWORD: {{ .Values.growthbook.email.hostPassword | default "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.growthbook.sso.enabled }}
  LICENSE_KEY: {{ .Values.growthbook.sso.licenseKey | default "" | b64enc | quote }}
  {{- end }}
stringData:
  {{- if .Values.growthbook.sso.enabled }}
  SSO_CONFIG: {{ .Values.growthbook.sso.ssoConfig | toJson | quote }}
  {{- end }}
{{- end }}
