apiVersion: v1
kind: ConfigMap
metadata:
  name: kutt
  labels:
    {{- include "kutt.labels" . | nindent 4 }}
data:
    {{- range $key, $val := .Values.env }}
    {{ $key  }}: {{ $val }}
    {{- end }}
