apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scoold.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "scoold.name" . }}
    helm.sh/chart: {{ include "scoold.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "scoold.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "scoold.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        {{/* This forces a restart if the configmap has changed */}}
        {{- if .Values.applicationConf }}
        configchecksum: {{ include (print .Template.BasePath "/secret.yaml") . | sha256sum | trunc 63 }}
        {{- end }}
    spec:
      volumes:
        {{- if .Values.applicationConf }}
        
        - name: appconfig
          secret:
            secretName: {{ include "scoold.name" . }}-config
            items:
              - key: "application.conf"
                path: "application.conf"
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: JAVA_OPTS
              value: "{{ .Values.javaOpts }}"
            {{- range $key, $val := .Values.extraEnvs }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          volumeMounts:
            {{- if .Values.applicationConf }}
            - name: appconfig
              mountPath: /scoold/config
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
