{{- if .Values.applicationConf }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scoold.name" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "scoold.name" . }}
    helm.sh/chart: {{ include "scoold.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  application.conf: {{ .Values.applicationConf | b64enc }}
{{- end -}}
