{{- if .Values.applicationConf }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scoold.name" . }}-config
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ include "scoold.name" . }}
type: Opaque
data:
  application.conf: {{ .Values.applicationConf | b64enc | quote }}
{{- end -}}
