{{ if and .Values.admin.create (not (eq .Values.admin.email "")) (not (eq .Values.admin.password "")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nocodb.admin.secretName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ include "nocodb.admin.emailKey" . }}: {{ .Values.admin.email | b64enc | quote }}
  {{ include "nocodb.admin.passwordKey" . }}: {{ .Values.admin.password | b64enc | quote }}
{{- end }}