{{- if and .Values.extraEnvSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nocodb.fullname" . }}-secrets
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
{{- range $key, $val := .Values.extraEnvSecrets }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}
{{- end }}
