name: GitGuardian Security Checks
on:
  push:
    branches-ignore:
      - quality-checks
  pull_request:
    branches:
      - main
concurrency:
  group: "${{ github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true
jobs:
  scanning:
    name: GitGuardian scan
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: GitGuardian scan
        uses: GitGuardian/gg-shield-action@master
        env:
          GITHUB_PUSH_BEFORE_SHA: "${{ github.event.before }}"
          GITHUB_PUSH_BASE_SHA: "${{ github.event.base }}"
          GITHUB_PULL_BASE_SHA: "${{ github.event.pull_request.base.sha }}"
          GITHUB_DEFAULT_BRANCH: "${{ github.event.repository.default_branch }}"
          GITGUARDIAN_API_KEY: "${{ secrets.GITGUARDIAN_API_KEY }}"
    